[workspace]
members = ["crates/graph", "crates/util"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
arrayvec = "0.7"
clap = { version = "4", features = ["derive"] }
clap-sys = { version = "0.4" }
crossbeam = "0.8"
glob = "0.3"
im = "15"
libc = "0.2"
midi20 = { path = "../midi2" }
rtaudio = "0.3"
scopeguard = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tesi-graph = { path = "crates/graph" }
tesi-util = { path = "crates/util" }
triple_buffer = "8"
