[package]
name = "tesi-graph"
version = "0.0.0"
edition = "2021"

[dependencies]
buffer = { workspace = true }
fifo =  { workspace = true }
util = { workspace = true }
processor = { workspace = true }
triple_buffer = { workspace = true }