[package]
name = "tesi-graph"
version = "0.0.0"
edition = "2021"

[dependencies]
batchbuffer =  { workspace = true }
buffer = { workspace = true }
util = { workspace = true }
processor = { workspace = true }
